language: node_js
node_js:
- '8'
script:
  - npm run build
  - echo "pixi.pomle.com" > build/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
    node: '8'
